### ISSUE TITLE
Create Incident class

### ISSUE THREAD

**Issue by alejgh** [Arquisoft/InciManager_i2b#2]
A new Incident class must be created. An incident has the following fields:
user name and password, incident name, description, location
(which will be automatically obtained if possible), tags (list of words separated by commas that will allow to categorize incidents), additional information (pictures, videos, etc).

This class must be an `@Entity`, like the agents in the first module, so a new IncidentRepository must be also created. Tests to check that these new class works correctly will also be needed.

**Comment by carmee-en** [comment]
Already on it!
