### ISSUE TITLE
Remove bootstrap CSS files

### ISSUE THREAD

**Issue by alejgh** [Arquisoft/InciManager_i2b#31]
We are using two bootstrap versions in our html views, 4.0 (included in the repository) and 3.x (from CDN). We must use just one version. Regardless of the version chosen we should use CDN instead of copying and pasting the original CSS file (not a big problem, but I don't like seeing our repo as written in CSS :sweat_smile:).

**Comment by ulitol97** [comment]
Taking care of it.
