### ISSUE TITLE
Implement GetIncidentsInfo post controller

### ISSUE THREAD

**Issue by alejgh** [Arquisoft/InciManager_i2b#4]
This controller will be used by agents to see the incidents they have submitted to the system (they will add their username and password to the request). For now we will query the database to look for all the incidents of the agent, so a new method in the IncidentRepository must be added (e.g. 'findAllByAgentUsername'). 
Returning a JSON object from the controller with all the incidents obtained by the repository will suffice right now. Maybe later we will also include a html view or something like so its easier for people to see the incidents.

This cannot be checked manually until #3 is finished, but some tests must be created. In these tests you can add some sample incidents to a mock database and check that the controller returns a valid json given an agent query.

**Comment by ulitol97** [comment]
Working on it

**Comment by alejgh** [comment]
#14 added some functionality to use in the controller, but we still need to implement the controller. 
The second paragraph in the description above states what must be done. We must also include the html view to display the incidents in a user friendly way.

**Comment by ulitol97** [comment]
Regarding the post controler, I think we should first check if the agent's credentials are not correct before querying the DB.
I was wondering about returning a not found HTTP responde in that case, for the moment at least.
What do you think?

**Comment by alejgh** [comment]
Yes, that is already implemented in the AgentsService class:
```java
	public boolean existsAgent(AgentInfo agent) throws Exception {
		LOG.info("Sending POST request to url: {}", agentsUrl);

		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.APPLICATION_JSON);

		JSONObject request = new JSONObject();
		request.put("login", agent.getUsername());
        request.put("password", agent.getPassword());
		request.put("kind", agent.getKind());

        HttpEntity<String> entity = new HttpEntity<String>(request.toString(), headers);

        ResponseEntity<String> response = new RestTemplate().exchange(agentsUrl, HttpMethod.POST, entity, String.class);
        HttpStatus responseCode = response.getStatusCode();
        return responseCode.equals(HttpStatus.OK);
	}
```

You can use that method from the controller before querying the db.

**Comment by alejgh** [comment]
If existsAgent returns false you can throw a new AgentNotFoundException (already implemented too) from the controller as you said.

**Comment by ulitol97** [comment]
I had just implemented it that way, nice to see it is OK 👍

**Comment by ulitol97** [comment]
A quick first idea of the HTML friendly interface, any suggestion or is it valid for now?
![aswform](https://user-images.githubusercontent.com/35763574/37559101-49c7d198-2a20-11e8-91ff-e58c4a48ea53.png)
![aswlist](https://user-images.githubusercontent.com/35763574/37559103-507e9292-2a20-11e8-986c-df123c016975.png)

**Comment by alejgh** [comment]
It looks really nice to me! You could show the incident properties if you want, but this is more than enough for the web interface.

**Comment by alejgh** [comment]
Just in case, in order to generate the JSON object you will return in the other controller you can do something like this:
```java
List<Incident> incidents = ...
ObjectMapper mapper = new ObjectMapper();
return mapper.writeValueAsString(incidents);
```
You don't need to manually create the json string, this is already done automatically by the IncidentSerializer class if you use the ObjectMapper.

**Comment by ulitol97** [comment]
😄😄 
You're right about the web view, I didn't show the properties (my bad), yet the 'Tags' and 'More Info' fields are shown listed as seen above (in case there are any tags or any extra info). If you think it's enough I'll go ahead with it.

**Comment by ulitol97** [comment]
Regarding the JSON, as far as I researched, if using @ResponseBody in the controller you may directly return a list, and the JSON conversion is performed automatically. Just in case, I just swapped my code and yours and tests were green without need of change ✌️. I'll soon try and merge everything so you can check it anyway.

**Comment by ulitol97** [comment]
PD: thanks for the piece of advice anyway
