### ISSUE TITLE
Incident form creation

### ISSUE THREAD

**Issue by carmee-en** [Arquisoft/InciManager_i2b#48]
We should also provide a way of creating incidents for users without bot interaction. The bot is very nice and we will keep it and by adding another form of interaction, we will improve our usability and accessibility.

There is already a post method that sends the created incident info. So the main focus will be the form view and the errors. **Tests have to be implemented as well.** 

When submitting a pull request for this, please include a snapshot of the view.

**Comment by ulitol97** [comment]
This may be a boring issue, but I'd like to take care of it, so I'll be assigning myself (for the sake of usability and accessibility 😝). Just tell me if you have any problem with this.
