### ISSUE TITLE
Cucumber tests

### ISSUE THREAD

**Issue by carmee-en** [Arquisoft/InciManager_i2b#49]
So far we have 5 user stories designed and 2 that are yet to be designed (see #47 ), and none of them have been implemented in Cucumber. This is required for the final deliverable.

The proposed workflow so we all work the same is:
- Somebody implements 3 of the already designed user stories in Cucumber.
- Somebody designs one of the missing user stories and implements 2 user stories.
- Somebody designs the other missing user stories and implements 2 user stories.

Write below if you prefer any alternative.

**Comment by alejgh** [comment]
I will start working on this. I'm going to implement the following user stories:
* Sensor reports incident.
* Person logs in.
* Person queries his incidents (new)

**Comment by carmee-en** [comment]
Starting now to work on this. I will implement:
- Person enters incorrect login data
- Entity reports incident
- Person reports incident

**Comment by ulitol97** [comment]
Taking care of this and implementing:
- Entity queries its incidents (new)
- Person checks the status of his incidents (new)
