### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by alejgh** [Arquisoft/InciManager_i2b#6]
We should include information in the readme, same as in the previous module (coverage and build status badges, team members and how to use the module).

**Comment by alejgh** [comment]
#21 Included the badges, team members, using Docker and creating an Incident. There is still more information to add to the readme:
* How to execute the module without using Docker.
* How to run the tests.
* How to query the incidents of an agents (both POST and GET requests).

**Comment by carmee-en** [comment]
@tejido18 added how to execute without docker via #41

**Comment by alejgh** [comment]
Yes, still need to add how to run tests and query the incidents.
